In [6]:
a1 = [1,2,3]
b1 = [4,5,6]
print (type(a1))
sum = 0
for i in range( len(a1)):
    sum+= a1[i] * b1[i]
print(sum)

<class 'list'>
32


In [ ]:
#elemente-wise Operation
import numpy as np
a=np.array([1,2,3])
b =np.array([4,5,6])
c= np.array([[1,2,3],[4,5,6]]) # 2D
#elemente-wise multiple
print(f"array a is  : {a}")
a =a*2
print(f"elemente-wise multiple of array a is  : {a}")

#elemente-wise add
print(f"2D array c is  : {c}")
c= c+2
print(f"elemente-wise multiple of 2D array c is  : {c}")

#sqrt
a=np.array([1,2,3])
np.sqrt(a)
#log log1 =0 , log e = 1
d= np.array([[1,2,3],[4,5,np.e]]) # 2D
np.log(d)
#log10  log10 of 10 =1 
e= np.array([[1,2,3],[4,5,10]]) # 2D
np.log10(e)

array a is  : [1 2 3]
elemente-wise multiple of array a is  : [2 4 6]
2D array c is  : [[1 2 3]
 [4 5 6]]
elemente-wise multiple of 2D array c is  : [[3 4 5]
 [6 7 8]]


array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 1.        ]])

Reshaping and aggregaton

In [24]:
import numpy as np

e = np.array([[1,2,3, 4,5,6]])
print(e.shape)
print(f"Lets Reshape  : {e}")
np.reshape(e, (3,2))

d = np.array([[1,2,3],[4,5,6]])
print(f"Lets take array d  :  {d}")
print(f"Lets Sum axis=0 column-wise  : ")
print(np.sum(d, axis=0))
print(f"Lets Sum axis=0 column-wise  : ")
print(np.sum(d, axis=1))
print(np.sum(d, axis=0))
print(f"Lets take Mean axis=0 column-wise  : ")
print(np.mean(d, axis=1))

(1, 6)
Lets Reshape  : [[1 2 3 4 5 6]]
Lets take array d  :  [[1 2 3]
 [4 5 6]]
Lets Sum axis=0 column-wise  : 
[5 7 9]
Lets Sum axis=0 column-wise  : 
[ 6 15]
[5 7 9]
Lets take Mean axis=0 column-wise  : 
[2. 5.]
